### ISSUE TITLE
不支持goland?

### ISSUE THREAD

**Issue by zcl0621** [silently9527/Toolkit#1]
你好 请问这个插件不支持goland么?
![QQ20210203-101419](https://user-images.githubusercontent.com/8233731/106688222-a6414900-6608-11eb-9060-ea90587172ba.png)

goland 版本 2020.3.2

**Comment by silently9527** [comment]
我没有用过goland  不确定    是不是你的版本比较高的原因   我用的是2019

**Comment by zcl0621** [comment]
那应该是的 估计是这个版本太新了 谢谢

**Comment by silently9527** [comment]
下次我release   把这个升级成高版本吧
