### ISSUE TITLE
希望补充版本要求

### ISSUE THREAD

**Issue by yiding-he** [silently9527/Toolkit#2]
如果对 InteiilJ 有版本要求，希望能在文档中加上

![idea64_SJ9585FlRD](https://user-images.githubusercontent.com/900606/106707171-c6ceca80-662b-11eb-9d1c-d6f7e74f90af.png)

![88MwYg9RwT](https://user-images.githubusercontent.com/900606/106707182-c9c9bb00-662b-11eb-8702-8f3487f38941.png)

**Comment by silently9527** [comment]
收到，最近我尽快处理下版本兼容的问题

**Comment by viveguan** [comment]
![image](https://user-images.githubusercontent.com/8788421/106864347-b0487200-6704-11eb-8801-246629ce436e.png)

**Comment by silently9527** [comment]
版本问题已经修复了   @viveguan @yiding-he   下载新的release版本试试

**Comment by silently9527** [comment]
如果还有问题    还请给我反馈一下

**Comment by yiding-he** [comment]
可以使用了
