### ISSUE TITLE
json字符串长度比较长的情况下会卡住

### ISSUE THREAD

**Issue by nnnnn0576** [silently9527/Toolkit#3]
在使用json格式化的时候 假如字符串长度比较长 整个插件卡住

**Comment by Sanit1** [comment]
测试了一下你的json 格式化代码 
可能是JBTextArea的问题？
还是我电脑太渣 内存太小了

**Comment by silently9527** [comment]
能把json字符串贴出来吗，   我这边复现一下

**Comment by nnnnn0576** [comment]
不管啥json字符串 只要整体字符串长度超过1000个 基本上就会这样

`[{"moduleName":"GoodsSalePC","remark":"弹窗售卖模块PC版","assets":["https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/css/cart.css","https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/scripts/cart.js"],"globalName":"$aliyun.components.GoodsPage","version":"0.6.10"},{"moduleName":"GoodsSalePC2","remark":"弹窗售卖模块PC版-橙色主题","assets":["https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/css/pc-orange-theme.css","https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/scripts/cart.js"],"globalName":"$aliyun.components.GoodsPage","version":"0.6.10"},{"moduleName":"GoodsSalePC3","remark":"弹窗售卖模块PC版-橙色主题-官网私域专用","assets":["https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/website/css/pc-orange-theme.css","https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/website/scripts/cart.js"],"globalName":"$aliyun.components.GoodsPage","version":"0.6.10"},{"moduleName":"GoodsSaleH5-","remark":"弹窗售卖模块H5版","assets":["https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/css/h5.css","https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/scripts/h5.js"],"globalName":"$aliyun.components.GoodsPage","version":"0.6.10"},{"moduleName":"GoodsSaleH5","remark":"弹窗售卖模块H5版","assets":["https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/css/h5.css","https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/scripts/h5.js"],"globalName":"$aliyun.components.GoodsPage","version":"0.6.10"},{"moduleName":"GoodsSaleH5-2","remark":"弹窗售卖模块H5版","assets":["https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/css/h5.css","https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/scripts/h5.js"],"globalName":"$aliyun.components.GoodsPage","version":"0.6.10"},{"moduleName":"GoodsSaleH5-3","remark":"弹窗售卖模块H5版-官网私域专用","assets":["https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/website/css/h5.css","https://g.alicdn.com/dawn/fe-goods-sdk/{{version}}/website/scripts/h5.js"],"globalName":"$aliyun.components.GoodsPage","version":"0.6.10"},{"moduleName":"popupBuy","remark":"弹窗售卖React组件","assets":["https://g.alicdn.com/nextbox/popup-buy/{{version}}/index.css","https://g.alicdn.com/nextbox/popup-buy/{{version}}/index.js"],"globalName":"ComponentsCollection.@ali/nextbox-popup-buy","version":"1.0.22"},{"moduleName":"shoppingCart","remark":"购物车组件","assets":["https://g.alicdn.com/dawn/aliyun-shopping-cart/{{version}}/css/miniCart.css","https://g.alicdn.com/dawn/aliyun-shopping-cart/{{version}}/js/miniCart.js"],"globalName":"$aliyunShoppingCart","version":"0.2.8"}]`

**Comment by silently9527** [comment]
![image](https://user-images.githubusercontent.com/5729336/108798689-5fbc8a00-75c9-11eb-8608-4953cfe2710f.png)
我这边没复现这个问题，格式化正常的

**Comment by nnnnn0576** [comment]
我刚提供的字符串还不够长 你试试这个

`{"@timestamp":"2021-01-22T15:53:55.815+08:00","@version":"1","message":"测试group异常,{}","logger_name":"com..admin.controller.GroupAdminController","thread_name":"http-nio-7070-exec-22","level":"ERROR","level_value":40000,"stack_trace":"retrofit2.HttpException: HTTP 403 Forbidden\n\tat com..core.http.SynchronousCallAdapterFactory$1.adapt(SynchronousCallAdapterFactory.java:41)\n\tat retrofit2.ServiceMethod.adapt(ServiceMethod.java:117)\n\tat retrofit2.Retrofit$1.invoke(Retrofit.java:149)\n\tat com.sun.proxy.$Proxy106.testGroup(Unknown Source)\n\tat com..admin.service.GroupService.testGroup(GroupService.java:36)\n\tat com..admin.controller.GroupAdminController.testGroup(GroupAdminController.java:130)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)\n\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)\n\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)\n\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)\n\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)\n\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:660)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:741)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat com..admin.filter.CorsFilter.doFilter(CorsFilter.java:36)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)\n\tat org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Thread.java:748)\n","logName":"admin"}`

**Comment by silently9527** [comment]
![image](https://user-images.githubusercontent.com/5729336/109111372-c087c600-7773-11eb-9efb-ea1aeed758a6.png)
正常的  我前几天发了个新的版本   你下载个新的版本试试
