### ISSUE TITLE
建议增加一个隐藏tab的功能和tab排序功能

### ISSUE THREAD

**Issue by xiamaoxuan** [silently9527/Toolkit#6]
1.我平时不会使用到那么多，所以想隐藏一下平时不用的工具
2.希望能够支持拖拽，把自己最经常使用的tab拖到前面

**Comment by silently9527** [comment]
收到，我考虑下

**Comment by silently9527** [comment]
新版本已经更新   在runAnything中输入命令     不用选择tab    欢迎试用 @xiamaoxuan
