### ISSUE TITLE
toolsets源码下载后本地安装插件失败

### ISSUE THREAD

**Issue by yubin19900** [silently9527/Toolkit#9]
idea版本:
![截屏2021-02-25 上午10 01 41](https://user-images.githubusercontent.com/5638600/109091901-953faf80-7750-11eb-8194-abdfe8b44e5a.png)
安装后:
![截屏2021-02-25 上午9 46 18](https://user-images.githubusercontent.com/5638600/109091920-a092db00-7750-11eb-9a43-43706ce8a899.png)
请大神帮忙看一下,是不是插件发布得不对还是别的原因

**Comment by silently9527** [comment]
你在仓库的release页面下载   我已经打好的包试试   ，有问题的话 给我反馈下

**Comment by ycdm** [comment]
> 你在仓库的release页面下载 我已经打好的包试试 ，有问题的话 给我反馈下

![image](https://user-images.githubusercontent.com/8018446/109249332-74e02580-7822-11eb-9a69-ad992501e804.png)
Android studio也是一样，空白一片

**Comment by yubin19900** [comment]
> 你在仓库的release页面下载 我已经打好的包试试 ，有问题的话 给我反馈下

可以了,谢谢
